title: "Memento"
description: "Thoughts on building things"
author: Matt Olson
url: "https://mlolson.github.io"
baseurl: "/blog"
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
